#服务器设定
server:
  # 端口设定
  port: 8080
  #配置JSP热部署
  servlet:
    jsp:
      init-parameters:
        development: true

spring:
  # 数据库连接配置
  datasource:
    url:  jdbc:mysql://106.13.45.1:3306/friend_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: amigo
    driver-class-name: com.mysql.cj.jdbc.Driver
  #mvc配置
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/
    static-path-pattern: /static/**
  #开启sping热部署
  devtools:
    restart:
      enabled: true
